[package]
name = "optiq-operator"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = { version = "0.92", features = ["runtime", "derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }