apiVersion: apps/v1
kind: Deployment
metadata:
  name: plansense
  namespace: optiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plansense
  template:
    metadata:
      labels:
        app: plansense
    spec:
      containers:
      - name: plansense
        image: optiq-ai/plansense:latest
        ports:
        - containerPort: 8082
        env:
        - name: RUST_LOG
          value: "info"
        - name: PG_CONNECTION
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: connection-string
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10