apiVersion: apps/v1
kind: Deployment
metadata:
  name: wokcore
  namespace: optiq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wokcore
  template:
    metadata:
      labels:
        app: wokcore
    spec:
      containers:
      - name: wokcore
        image: optiq-ai/wokcore:latest
        ports:
        - containerPort: 8081
        env:
        - name: RUST_LOG
          value: "info"
        - name: WOK_DESIGN_SPACE
          value: "quindecillion"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          httpGet-three:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10