apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queryplans.optiq.ai
spec:
  group: optiq.ai
  names:
    kind: QueryPlan
    plural: queryplans
    singular: queryplan
    shortNames:
    - qp
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              queryId:
                type: string
              sql:
                type: string
              planHash:
                type: string
              parameters:
                type: array
                items:
                  type: integer
          status:
            type: object
            properties:
              latencyMs:
                type: integer
              recommendedPlan:
                type: string